gateways:
  local:
    connection:
      type: duckdb
      database: db/analytics.duckdb

default_gateway: local

model_defaults:
  dialect: duckdb

# Bloque requerido para que la CLI ejecute la integración de PRs
cicd_bot:
  type: github