gateways:
  local:
    connection:
      type: duckdb
      database: db/analytics.duckdb

  snowflake:
    connection:
      type: snowflake
      account: mu75918.us-east-2.aws
      user: martin.berlusconi@allata.com
      authenticator: externalbrowser
      role: DBT_PIPELINE_DEVELOPER
      warehouse: CICD
      database: POC_CICD
      concurrent_tasks: 1
      
    state_schema: SQLMESH_STATE

default_gateway: snowflake

model_defaults:
  dialect: snowflake

cicd_bot:
  type: github